<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN5CD14688N6" failures="1" tests="3" name="Test" time="22.268" errors="0" timestamp="2023-08-04T14:48:07 IST">
  <testcase classname="com.tests.ValidationEpic1" name="validateOfferesIsSelected2" time="0.118">
    <skipped/>
  </testcase> <!-- validateOfferesIsSelected2 -->
  <testcase classname="com.tests.ValidationEpic1" name="validateOfferesIsSelected2" time="0.019">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.pages.HomePage.negative(HomePage.java:64)
at com.tests.ValidationEpic1.validateOfferesIsSelected2(ValidationEpic1.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateOfferesIsSelected2 -->
  <testcase classname="com.tests.ValidationEpic1" name="validateHotelIsSelected2" time="0.691"/>
</testsuite> <!-- Test -->
